version: '3.8'
services:
    tmp:
        image: busybox
        container_name: container_files
        command: chmod -R 777 /opt/homebrew/var/db/redis/ && chmod -R 777 /var/tmp/vissv2/ && chmod -R 777 /var/run/
        volumes:
            - /opt/homebrew/var/db/redis/
            - /var/tmp/vissv2/
            - /var/run/
    redis:
        image: redis
        container_name: app_redis
        privileged: true
        user: root
        command: redis-server /etc/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/etc/redis.conf
        volumes_from:
            - tmp

    feeder:
        container_name: feeder
        privileged: true
        volumes:
            - ./redis/redisDB.sock:/var/tmp/vissv2/redisDB.sock
        build:
             context: .  # context set to repo root
             target: feeder
        volumes_from:
         - tmp
        entrypoint: [ /app/feeder ]