version: '3.8'
services:
  tmp:
    image: busybox
    container_name: container_volumes
    user: root
    command: >
      chmod -R 777 /tmp/docker/ &&
      chmod -R 777 /opt/homebrew/var/db/redis/

    volumes:
      - /tmp/docker/
      - /opt/homebrew/var/db/redis/

  redis:
    image: redis
    container_name: app_redis
    privileged: true
    user: root
    command: redis-server /etc/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
    volumes_from:
      - tmp