version: '3.7'
services:
    servercore:
        build:
            context: .  # context set to repo root
            dockerfile: server/server_core/Dockerfile
        environment:
            - GEN2MODULEIP=srvcore
        volumes:
            - logdata:/app/logs
        networks:
            internal:
                aliases:
                    - srvcore
    servicemgr:
        build:
            context: .  # context set to repo root
            dockerfile: server/service_mgr/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
           
    atserver:
        build:
            context: .  # context set to repo root
            dockerfile: server/at_server/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8600:8600"
        networks:
            internal:
                aliases:
                    - atserver
            external:
                aliases:
                    - atserver
    agtserver:
        build:
            context: .  # context set to repo root
            dockerfile: server/agt_server/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "7500:7500"
        networks:
            internal:
                aliases:
                    - agtserver
            external:
                aliases:
                    - agtserver
                
    httpmgr:
        build:
            context: .  # context set to repo root
            dockerfile: server/http_mgr/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        ports:
            - "8888:8888"
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
            - external
    wsmgr:
        build:
            context: .  # context set to repo root
            dockerfile: server/ws_mgr/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8080:8080"
        networks:
            - internal
            - external

networks:
    internal:
    external:
volumes:
    logdata:
