version: '3.7'
services:
    servercore:
        build:
            context: .  # context set to repo root
            dockerfile: server/server-core/Dockerfile
        volumes:
            - logdata:/app/logs
        networks:
            internal:
                aliases:
                    - srvcore
    servicemgr:
        build:
            context: .  # context set to repo root
            dockerfile: server/servicemgr/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
    atserver:
        build:
            context: .  # context set to repo root
            dockerfile: server/atserver/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8600:8600"
        networks:
            - internal
            - external
    httpmgr:
        build:
            context: .  # context set to repo root
            dockerfile: server/httpmgr/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        ports:
            - "8888:8888"
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
            - external
    wsmgr:
        build:
            context: .  # context set to repo root
            dockerfile: server/wsmgr/Dockerfile
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8080:8080"
        networks:
            - internal
            - external

networks:
    internal:
    external:
volumes:
    logdata:
