version: '3.7'
services:
    server_core:
        build:
            context: .  # context set to repo root
            target: server_core
        environment:
            - GEN2MODULEIP=atserver
        volumes:
            - logdata:/app/logs
        networks:
            internal:
                aliases:
                    - srvcore
    mgr_service:
        build:
            context: .  # context set to repo root
            target: service_mgr
        depends_on:
            - "server_core"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            internal:
                aliases:
                    - servicemgr
           
    server_at:
        build:
            context: .  # context set to repo root
            target: at_server
        depends_on:
            - "server_core"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8600:8600"
        networks:
            internal:
                aliases:
                    - atserver
            external:
                aliases:
                    - atserver
    server_agt:
        build:
            context: .  # context set to repo root
            target: agt_server
        depends_on:
            - "server_core"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "7500:7500"
        networks:
            internal:
                aliases:
                    - agtserver
            external:
                aliases:
                    - agtserver
                
    mgr_http:
        build:
            context: .  # context set to repo root
            target: http_mgr
        depends_on:
            - "server_core"
        volumes:
            - logdata:/app/logs
        ports:
            - "8888:8888"
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
            - external

    mgr_ws:
        build:
            context: .  # context set to repo root
            target: ws_mgr
        depends_on:
            - "server_core"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8080:8080"
        networks:
            - internal
            - external

    mgr_mqtt:
        build:
            context: .  # context set to repo root
            target: mqtt_mgr
        depends_on:
            - "server_core"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports: 
            - "1883:1883"
        networks:
            - internal
            - external

    server_web:
        image: 'httpd:2.4-alpine'
        depends_on:
            - "server_core"
        volumes:
            - ./client/client-1.0/Javascript/:/usr/local/apache2/htdocs/
        ports:
            - "10080:80"
        networks:
            - external

networks:
    internal:
    external:
volumes:
    logdata:
