version: '3.7'
services:
    servercore:
        build:
            context: .  # context set to repo root
            target: server_core
        environment:
            - GEN2MODULEIP=atserver
        volumes:
            - logdata:/app/logs
        networks:
            internal:
                aliases:
                    - srvcore
    servicemgr:
        build:
            context: .  # context set to repo root
            target: service_mgr
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            internal:
                aliases:
                    - servicemgr
           
    atserver:
        build:
            context: .  # context set to repo root
            target: at_server
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8600:8600"
        networks:
            internal:
                aliases:
                    - atserver
            external:
                aliases:
                    - atserver
    agtserver:
        build:
            context: .  # context set to repo root
            target: agt_server
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "7500:7500"
        networks:
            internal:
                aliases:
                    - agtserver
            external:
                aliases:
                    - agtserver
                
    httpmgr:
        build:
            context: .  # context set to repo root
            target: http_mgr
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        ports:
            - "8888:8888"
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
            - external
    wsmgr:
        build:
            context: .  # context set to repo root
            target: ws_mgr
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        ports:
            - "8080:8080"
        networks:
            - internal
            - external
    mqttmgr:
        build:
            context: .  # context set to repo root
            target: mqtt_mgr
        depends_on:
            - "servercore"
        volumes:
            - logdata:/app/logs
        environment:
            - GEN2MODULEIP=srvcore
        networks:
            - internal
            - external

networks:
    internal:
    external:
volumes:
    logdata:
