// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: VISSv2.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package grpcProtobufMessages;

@kotlin.jvm.JvmName("-initializedataPackages")
public inline fun dataPackages(block: grpcProtobufMessages.DataPackagesKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.DataPackages =
  grpcProtobufMessages.DataPackagesKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.DataPackages.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpcProtobufMessages.DataPackages`
 */
public object DataPackagesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpcProtobufMessages.VISSv2OuterClass.DataPackages.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.DataPackages.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.DataPackages = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .grpcProtobufMessages.DataPackages.DataPackage Data = 1;`
     */
     public val data: com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage, DataProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDataList()
      )
    /**
     * `repeated .grpcProtobufMessages.DataPackages.DataPackage Data = 1;`
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addData")
    public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage, DataProxy>.add(value: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage) {
      _builder.addData(value)
    }
    /**
     * `repeated .grpcProtobufMessages.DataPackages.DataPackage Data = 1;`
     * @param value The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage, DataProxy>.plusAssign(value: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage) {
      add(value)
    }
    /**
     * `repeated .grpcProtobufMessages.DataPackages.DataPackage Data = 1;`
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllData")
    public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage, DataProxy>.addAll(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage>) {
      _builder.addAllData(values)
    }
    /**
     * `repeated .grpcProtobufMessages.DataPackages.DataPackage Data = 1;`
     * @param values The data to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage, DataProxy>.plusAssign(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage>) {
      addAll(values)
    }
    /**
     * `repeated .grpcProtobufMessages.DataPackages.DataPackage Data = 1;`
     * @param index The index to set the value at.
     * @param value The data to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setData")
    public operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage, DataProxy>.set(index: kotlin.Int, value: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage) {
      _builder.setData(index, value)
    }
    /**
     * `repeated .grpcProtobufMessages.DataPackages.DataPackage Data = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearData")
    public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage, DataProxy>.clear() {
      _builder.clearData()
    }
  }
  @kotlin.jvm.JvmName("-initializedataPackage")
  public inline fun dataPackage(block: grpcProtobufMessages.DataPackagesKt.DataPackageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage =
    grpcProtobufMessages.DataPackagesKt.DataPackageKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `grpcProtobufMessages.DataPackages.DataPackage`
   */
  public object DataPackageKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage = _builder.build()

      /**
       * `optional string Path = 1;`
       */
      public var path: kotlin.String
        @JvmName("getPath")
        get() = _builder.getPath()
        @JvmName("setPath")
        set(value) {
          _builder.setPath(value)
        }
      /**
       * `optional string Path = 1;`
       */
      public fun clearPath() {
        _builder.clearPath()
      }
      /**
       * `optional string Path = 1;`
       * @return Whether the path field is set.
       */
      public fun hasPath(): kotlin.Boolean {
        return _builder.hasPath()
      }

      /**
       * <code>optional int32 PathC = 2;</code>
       */
      public var pathC: kotlin.Int
        @JvmName("getPathC")
        get() = _builder.getPathC()
        @JvmName("setPathC")
        set(value) {
          _builder.setPathC(value)
        }
      /**
       * `optional int32 PathC = 2;`
       */
      public fun clearPathC() {
        _builder.clearPathC()
      }
      /**
       * `optional int32 PathC = 2;`
       * @return Whether the pathC field is set.
       */
      public fun hasPathC(): kotlin.Boolean {
        return _builder.hasPathC()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class DpProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .grpcProtobufMessages.DataPackages.DataPackage.DataPoint Dp = 3;`
       */
       public val dp: com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint, DpProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.getDpList()
        )
      /**
       * `repeated .grpcProtobufMessages.DataPackages.DataPackage.DataPoint Dp = 3;`
       * @param value The dp to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addDp")
      public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint, DpProxy>.add(value: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint) {
        _builder.addDp(value)
      }
      /**
       * `repeated .grpcProtobufMessages.DataPackages.DataPackage.DataPoint Dp = 3;`
       * @param value The dp to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignDp")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint, DpProxy>.plusAssign(value: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint) {
        add(value)
      }
      /**
       * `repeated .grpcProtobufMessages.DataPackages.DataPackage.DataPoint Dp = 3;`
       * @param values The dp to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllDp")
      public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint, DpProxy>.addAll(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint>) {
        _builder.addAllDp(values)
      }
      /**
       * `repeated .grpcProtobufMessages.DataPackages.DataPackage.DataPoint Dp = 3;`
       * @param values The dp to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllDp")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint, DpProxy>.plusAssign(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint>) {
        addAll(values)
      }
      /**
       * `repeated .grpcProtobufMessages.DataPackages.DataPackage.DataPoint Dp = 3;`
       * @param index The index to set the value at.
       * @param value The dp to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setDp")
      public operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint, DpProxy>.set(index: kotlin.Int, value: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint) {
        _builder.setDp(index, value)
      }
      /**
       * `repeated .grpcProtobufMessages.DataPackages.DataPackage.DataPoint Dp = 3;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearDp")
      public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint, DpProxy>.clear() {
        _builder.clearDp()
      }
    }
    @kotlin.jvm.JvmName("-initializedataPoint")
    public inline fun dataPoint(block: grpcProtobufMessages.DataPackagesKt.DataPackageKt.DataPointKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint =
      grpcProtobufMessages.DataPackagesKt.DataPackageKt.DataPointKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint.newBuilder()).apply { block() }._build()
    /**
     * Protobuf type `grpcProtobufMessages.DataPackages.DataPackage.DataPoint`
     */
    public object DataPointKt {
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      @com.google.protobuf.kotlin.ProtoDslMarker
      public class Dsl private constructor(
        private val _builder: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint.Builder
      ) {
        public companion object {
          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint = _builder.build()

        /**
         * `string Value = 1;`
         */
        public var value: kotlin.String
          @JvmName("getValue")
          get() = _builder.getValue()
          @JvmName("setValue")
          set(value) {
            _builder.setValue(value)
          }
        /**
         * `string Value = 1;`
         */
        public fun clearValue() {
          _builder.clearValue()
        }

        /**
         * `optional string Ts = 2;`
         */
        public var ts: kotlin.String
          @JvmName("getTs")
          get() = _builder.getTs()
          @JvmName("setTs")
          set(value) {
            _builder.setTs(value)
          }
        /**
         * `optional string Ts = 2;`
         */
        public fun clearTs() {
          _builder.clearTs()
        }
        /**
         * `optional string Ts = 2;`
         * @return Whether the ts field is set.
         */
        public fun hasTs(): kotlin.Boolean {
          return _builder.hasTs()
        }

        /**
         * <code>optional int32 TsC = 3;</code>
         */
        public var tsC: kotlin.Int
          @JvmName("getTsC")
          get() = _builder.getTsC()
          @JvmName("setTsC")
          set(value) {
            _builder.setTsC(value)
          }
        /**
         * `optional int32 TsC = 3;`
         */
        public fun clearTsC() {
          _builder.clearTsC()
        }
        /**
         * `optional int32 TsC = 3;`
         * @return Whether the tsC field is set.
         */
        public fun hasTsC(): kotlin.Boolean {
          return _builder.hasTsC()
        }
      }
    }
  }
}
public inline fun grpcProtobufMessages.VISSv2OuterClass.DataPackages.copy(block: grpcProtobufMessages.DataPackagesKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.DataPackages =
  grpcProtobufMessages.DataPackagesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.copy(block: grpcProtobufMessages.DataPackagesKt.DataPackageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage =
  grpcProtobufMessages.DataPackagesKt.DataPackageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint.copy(block: grpcProtobufMessages.DataPackagesKt.DataPackageKt.DataPointKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.DataPackages.DataPackage.DataPoint =
  grpcProtobufMessages.DataPackagesKt.DataPackageKt.DataPointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

