// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: VISSv2.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package grpcProtobufMessages;

@kotlin.jvm.JvmName("-initializeerrorResponseMessage")
public inline fun errorResponseMessage(block: grpcProtobufMessages.ErrorResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage =
  grpcProtobufMessages.ErrorResponseMessageKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpcProtobufMessages.ErrorResponseMessage`
 */
public object ErrorResponseMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage = _builder.build()

    /**
     * `string Number = 1;`
     */
    public var number: kotlin.String
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * `string Number = 1;`
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }

    /**
     * `optional string Reason = 2;`
     */
    public var reason: kotlin.String
      @JvmName("getReason")
      get() = _builder.getReason()
      @JvmName("setReason")
      set(value) {
        _builder.setReason(value)
      }
    /**
     * `optional string Reason = 2;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
    /**
     * `optional string Reason = 2;`
     * @return Whether the reason field is set.
     */
    public fun hasReason(): kotlin.Boolean {
      return _builder.hasReason()
    }

    /**
     * `optional string Message = 3;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `optional string Message = 3;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * `optional string Message = 3;`
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }
  }
}
public inline fun grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage.copy(block: grpcProtobufMessages.ErrorResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage =
  grpcProtobufMessages.ErrorResponseMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

