// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: VISSv2.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package grpcProtobufMessages;

@kotlin.jvm.JvmName("-initializefilterExpressions")
public inline fun filterExpressions(block: grpcProtobufMessages.FilterExpressionsKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions =
  grpcProtobufMessages.FilterExpressionsKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpcProtobufMessages.FilterExpressions`
 */
public object FilterExpressionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FilterExpProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression FilterExp = 1;`
     */
     public val filterExp: com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression, FilterExpProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFilterExpList()
      )
    /**
     * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression FilterExp = 1;`
     * @param value The filterExp to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFilterExp")
    public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression, FilterExpProxy>.add(value: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression) {
      _builder.addFilterExp(value)
    }
    /**
     * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression FilterExp = 1;`
     * @param value The filterExp to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFilterExp")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression, FilterExpProxy>.plusAssign(value: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression) {
      add(value)
    }
    /**
     * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression FilterExp = 1;`
     * @param values The filterExp to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFilterExp")
    public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression, FilterExpProxy>.addAll(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression>) {
      _builder.addAllFilterExp(values)
    }
    /**
     * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression FilterExp = 1;`
     * @param values The filterExp to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFilterExp")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression, FilterExpProxy>.plusAssign(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression>) {
      addAll(values)
    }
    /**
     * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression FilterExp = 1;`
     * @param index The index to set the value at.
     * @param value The filterExp to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFilterExp")
    public operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression, FilterExpProxy>.set(index: kotlin.Int, value: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression) {
      _builder.setFilterExp(index, value)
    }
    /**
     * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression FilterExp = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFilterExp")
    public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression, FilterExpProxy>.clear() {
      _builder.clearFilterExp()
    }
  }
  @kotlin.jvm.JvmName("-initializefilterExpression")
  public inline fun filterExpression(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression =
    grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression`
   */
  public object FilterExpressionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression = _builder.build()

      /**
       * `.grpcProtobufMessages.FilterExpressions.FilterExpression.FilterType FType = 1;`
       */
      public var fType: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterType
        @JvmName("getFType")
        get() = _builder.getFType()
        @JvmName("setFType")
        set(value) {
          _builder.setFType(value)
        }
      public var fTypeValue: kotlin.Int
        @JvmName("getFTypeValue")
        get() = _builder.getFTypeValue()
        @JvmName("setFTypeValue")
        set(value) {
          _builder.setFTypeValue(value)
        }
      /**
       * `.grpcProtobufMessages.FilterExpressions.FilterExpression.FilterType FType = 1;`
       */
      public fun clearFType() {
        _builder.clearFType()
      }

      /**
       * `.grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue Value = 2;`
       */
      public var value: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue
        @JvmName("getValue")
        get() = _builder.getValue()
        @JvmName("setValue")
        set(value) {
          _builder.setValue(value)
        }
      /**
       * `.grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue Value = 2;`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
      /**
       * `.grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue Value = 2;`
       * @return Whether the value field is set.
       */
      public fun hasValue(): kotlin.Boolean {
        return _builder.hasValue()
      }
    }
    @kotlin.jvm.JvmName("-initializefilterValue")
    public inline fun filterValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue =
      grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.newBuilder()).apply { block() }._build()
    /**
     * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue`
     */
    public object FilterValueKt {
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      @com.google.protobuf.kotlin.ProtoDslMarker
      public class Dsl private constructor(
        private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.Builder
      ) {
        public companion object {
          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue = _builder.build()

        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.PathsValue ValuePaths = 1;`
         */
        public var valuePaths: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue
          @JvmName("getValuePaths")
          get() = _builder.getValuePaths()
          @JvmName("setValuePaths")
          set(value) {
            _builder.setValuePaths(value)
          }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.PathsValue ValuePaths = 1;`
         */
        public fun clearValuePaths() {
          _builder.clearValuePaths()
        }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.PathsValue ValuePaths = 1;`
         * @return Whether the valuePaths field is set.
         */
        public fun hasValuePaths(): kotlin.Boolean {
          return _builder.hasValuePaths()
        }
        public val FilterValueKt.Dsl.valuePathsOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue?
          get() = _builder.valuePathsOrNull

        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.TimebasedValue ValueTimebased = 2;`
         */
        public var valueTimebased: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue
          @JvmName("getValueTimebased")
          get() = _builder.getValueTimebased()
          @JvmName("setValueTimebased")
          set(value) {
            _builder.setValueTimebased(value)
          }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.TimebasedValue ValueTimebased = 2;`
         */
        public fun clearValueTimebased() {
          _builder.clearValueTimebased()
        }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.TimebasedValue ValueTimebased = 2;`
         * @return Whether the valueTimebased field is set.
         */
        public fun hasValueTimebased(): kotlin.Boolean {
          return _builder.hasValueTimebased()
        }
        public val FilterValueKt.Dsl.valueTimebasedOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue?
          get() = _builder.valueTimebasedOrNull

        /**
         * An uninstantiable, behaviorless type to represent the field in
         * generics.
         */
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        public class ValueRangeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
        /**
         * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue ValueRange = 3;`
         */
         public val valueRange: com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue, ValueRangeProxy>
          @kotlin.jvm.JvmSynthetic
          get() = com.google.protobuf.kotlin.DslList(
            _builder.getValueRangeList()
          )
        /**
         * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue ValueRange = 3;`
         * @param value The valueRange to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("addValueRange")
        public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue, ValueRangeProxy>.add(value: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue) {
          _builder.addValueRange(value)
        }
        /**
         * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue ValueRange = 3;`
         * @param value The valueRange to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("plusAssignValueRange")
        @Suppress("NOTHING_TO_INLINE")
        public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue, ValueRangeProxy>.plusAssign(value: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue) {
          add(value)
        }
        /**
         * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue ValueRange = 3;`
         * @param values The valueRange to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("addAllValueRange")
        public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue, ValueRangeProxy>.addAll(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue>) {
          _builder.addAllValueRange(values)
        }
        /**
         * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue ValueRange = 3;`
         * @param values The valueRange to add.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("plusAssignAllValueRange")
        @Suppress("NOTHING_TO_INLINE")
        public inline operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue, ValueRangeProxy>.plusAssign(values: kotlin.collections.Iterable<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue>) {
          addAll(values)
        }
        /**
         * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue ValueRange = 3;`
         * @param index The index to set the value at.
         * @param value The valueRange to set.
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("setValueRange")
        public operator fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue, ValueRangeProxy>.set(index: kotlin.Int, value: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue) {
          _builder.setValueRange(index, value)
        }
        /**
         * `repeated .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue ValueRange = 3;`
         */
        @kotlin.jvm.JvmSynthetic
        @kotlin.jvm.JvmName("clearValueRange")
        public fun com.google.protobuf.kotlin.DslList<grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue, ValueRangeProxy>.clear() {
          _builder.clearValueRange()
        }

        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.ChangeValue ValueChange = 4;`
         */
        public var valueChange: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue
          @JvmName("getValueChange")
          get() = _builder.getValueChange()
          @JvmName("setValueChange")
          set(value) {
            _builder.setValueChange(value)
          }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.ChangeValue ValueChange = 4;`
         */
        public fun clearValueChange() {
          _builder.clearValueChange()
        }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.ChangeValue ValueChange = 4;`
         * @return Whether the valueChange field is set.
         */
        public fun hasValueChange(): kotlin.Boolean {
          return _builder.hasValueChange()
        }
        public val FilterValueKt.Dsl.valueChangeOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue?
          get() = _builder.valueChangeOrNull

        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.CurvelogValue ValueCurvelog = 5;`
         */
        public var valueCurvelog: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue
          @JvmName("getValueCurvelog")
          get() = _builder.getValueCurvelog()
          @JvmName("setValueCurvelog")
          set(value) {
            _builder.setValueCurvelog(value)
          }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.CurvelogValue ValueCurvelog = 5;`
         */
        public fun clearValueCurvelog() {
          _builder.clearValueCurvelog()
        }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.CurvelogValue ValueCurvelog = 5;`
         * @return Whether the valueCurvelog field is set.
         */
        public fun hasValueCurvelog(): kotlin.Boolean {
          return _builder.hasValueCurvelog()
        }
        public val FilterValueKt.Dsl.valueCurvelogOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue?
          get() = _builder.valueCurvelogOrNull

        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.HistoryValue ValueHistory = 6;`
         */
        public var valueHistory: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue
          @JvmName("getValueHistory")
          get() = _builder.getValueHistory()
          @JvmName("setValueHistory")
          set(value) {
            _builder.setValueHistory(value)
          }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.HistoryValue ValueHistory = 6;`
         */
        public fun clearValueHistory() {
          _builder.clearValueHistory()
        }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.HistoryValue ValueHistory = 6;`
         * @return Whether the valueHistory field is set.
         */
        public fun hasValueHistory(): kotlin.Boolean {
          return _builder.hasValueHistory()
        }
        public val FilterValueKt.Dsl.valueHistoryOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue?
          get() = _builder.valueHistoryOrNull

        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue ValueStaticMetadata = 7;`
         */
        public var valueStaticMetadata: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue
          @JvmName("getValueStaticMetadata")
          get() = _builder.getValueStaticMetadata()
          @JvmName("setValueStaticMetadata")
          set(value) {
            _builder.setValueStaticMetadata(value)
          }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue ValueStaticMetadata = 7;`
         */
        public fun clearValueStaticMetadata() {
          _builder.clearValueStaticMetadata()
        }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue ValueStaticMetadata = 7;`
         * @return Whether the valueStaticMetadata field is set.
         */
        public fun hasValueStaticMetadata(): kotlin.Boolean {
          return _builder.hasValueStaticMetadata()
        }
        public val FilterValueKt.Dsl.valueStaticMetadataOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue?
          get() = _builder.valueStaticMetadataOrNull

        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue ValueDynamicMetadata = 8;`
         */
        public var valueDynamicMetadata: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue
          @JvmName("getValueDynamicMetadata")
          get() = _builder.getValueDynamicMetadata()
          @JvmName("setValueDynamicMetadata")
          set(value) {
            _builder.setValueDynamicMetadata(value)
          }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue ValueDynamicMetadata = 8;`
         */
        public fun clearValueDynamicMetadata() {
          _builder.clearValueDynamicMetadata()
        }
        /**
         * `optional .grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue ValueDynamicMetadata = 8;`
         * @return Whether the valueDynamicMetadata field is set.
         */
        public fun hasValueDynamicMetadata(): kotlin.Boolean {
          return _builder.hasValueDynamicMetadata()
        }
        public val FilterValueKt.Dsl.valueDynamicMetadataOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue?
          get() = _builder.valueDynamicMetadataOrNull
      }
      @kotlin.jvm.JvmName("-initializepathsValue")
      public inline fun pathsValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.PathsValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.PathsValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.PathsValue`
       */
      public object PathsValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue = _builder.build()

          /**
           * An uninstantiable, behaviorless type to represent the field in
           * generics.
           */
          @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
          public class RelativePathProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
          /**
           * `repeated string RelativePath = 1;`
           * @return A list containing the relativePath.
           */
          public val relativePath: com.google.protobuf.kotlin.DslList<kotlin.String, RelativePathProxy>
          @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
            get() = com.google.protobuf.kotlin.DslList(
              _builder.getRelativePathList()
            )
          /**
           * `repeated string RelativePath = 1;`
           * @param value The relativePath to add.
           */
          @kotlin.jvm.JvmSynthetic
          @kotlin.jvm.JvmName("addRelativePath")
          public fun com.google.protobuf.kotlin.DslList<kotlin.String, RelativePathProxy>.add(value: kotlin.String) {
            _builder.addRelativePath(value)
          }
          /**
           * `repeated string RelativePath = 1;`
           * @param value The relativePath to add.
           */
          @kotlin.jvm.JvmSynthetic
          @kotlin.jvm.JvmName("plusAssignRelativePath")
          @Suppress("NOTHING_TO_INLINE")
          public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RelativePathProxy>.plusAssign(value: kotlin.String) {
            add(value)
          }
          /**
           * `repeated string RelativePath = 1;`
           * @param values The relativePath to add.
           */
          @kotlin.jvm.JvmSynthetic
          @kotlin.jvm.JvmName("addAllRelativePath")
          public fun com.google.protobuf.kotlin.DslList<kotlin.String, RelativePathProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
            _builder.addAllRelativePath(values)
          }
          /**
           * `repeated string RelativePath = 1;`
           * @param values The relativePath to add.
           */
          @kotlin.jvm.JvmSynthetic
          @kotlin.jvm.JvmName("plusAssignAllRelativePath")
          @Suppress("NOTHING_TO_INLINE")
          public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RelativePathProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
            addAll(values)
          }
          /**
           * `repeated string RelativePath = 1;`
           * @param index The index to set the value at.
           * @param value The relativePath to set.
           */
          @kotlin.jvm.JvmSynthetic
          @kotlin.jvm.JvmName("setRelativePath")
          public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RelativePathProxy>.set(index: kotlin.Int, value: kotlin.String) {
            _builder.setRelativePath(index, value)
          }/**
           * `repeated string RelativePath = 1;`
           */
          @kotlin.jvm.JvmSynthetic
          @kotlin.jvm.JvmName("clearRelativePath")
          public fun com.google.protobuf.kotlin.DslList<kotlin.String, RelativePathProxy>.clear() {
            _builder.clearRelativePath()
          }}
      }
      @kotlin.jvm.JvmName("-initializetimebasedValue")
      public inline fun timebasedValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.TimebasedValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.TimebasedValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.TimebasedValue`
       */
      public object TimebasedValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue = _builder.build()

          /**
           * `string Period = 1;`
           */
          public var period: kotlin.String
            @JvmName("getPeriod")
            get() = _builder.getPeriod()
            @JvmName("setPeriod")
            set(value) {
              _builder.setPeriod(value)
            }
          /**
           * `string Period = 1;`
           */
          public fun clearPeriod() {
            _builder.clearPeriod()
          }
        }
      }
      @kotlin.jvm.JvmName("-initializerangeValue")
      public inline fun rangeValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.RangeValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.RangeValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.RangeValue`
       */
      public object RangeValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue = _builder.build()

          /**
           * `string LogicOperator = 1;`
           */
          public var logicOperator: kotlin.String
            @JvmName("getLogicOperator")
            get() = _builder.getLogicOperator()
            @JvmName("setLogicOperator")
            set(value) {
              _builder.setLogicOperator(value)
            }
          /**
           * `string LogicOperator = 1;`
           */
          public fun clearLogicOperator() {
            _builder.clearLogicOperator()
          }

          /**
           * `string Boundary = 2;`
           */
          public var boundary: kotlin.String
            @JvmName("getBoundary")
            get() = _builder.getBoundary()
            @JvmName("setBoundary")
            set(value) {
              _builder.setBoundary(value)
            }
          /**
           * `string Boundary = 2;`
           */
          public fun clearBoundary() {
            _builder.clearBoundary()
          }
        }
      }
      @kotlin.jvm.JvmName("-initializechangeValue")
      public inline fun changeValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.ChangeValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.ChangeValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.ChangeValue`
       */
      public object ChangeValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue = _builder.build()

          /**
           * `string LogicOperator = 1;`
           */
          public var logicOperator: kotlin.String
            @JvmName("getLogicOperator")
            get() = _builder.getLogicOperator()
            @JvmName("setLogicOperator")
            set(value) {
              _builder.setLogicOperator(value)
            }
          /**
           * `string LogicOperator = 1;`
           */
          public fun clearLogicOperator() {
            _builder.clearLogicOperator()
          }

          /**
           * `string Diff = 2;`
           */
          public var diff: kotlin.String
            @JvmName("getDiff")
            get() = _builder.getDiff()
            @JvmName("setDiff")
            set(value) {
              _builder.setDiff(value)
            }
          /**
           * `string Diff = 2;`
           */
          public fun clearDiff() {
            _builder.clearDiff()
          }
        }
      }
      @kotlin.jvm.JvmName("-initializecurvelogValue")
      public inline fun curvelogValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.CurvelogValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.CurvelogValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.CurvelogValue`
       */
      public object CurvelogValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue = _builder.build()

          /**
           * `string MaxErr = 1;`
           */
          public var maxErr: kotlin.String
            @JvmName("getMaxErr")
            get() = _builder.getMaxErr()
            @JvmName("setMaxErr")
            set(value) {
              _builder.setMaxErr(value)
            }
          /**
           * `string MaxErr = 1;`
           */
          public fun clearMaxErr() {
            _builder.clearMaxErr()
          }

          /**
           * `string BufSize = 2;`
           */
          public var bufSize: kotlin.String
            @JvmName("getBufSize")
            get() = _builder.getBufSize()
            @JvmName("setBufSize")
            set(value) {
              _builder.setBufSize(value)
            }
          /**
           * `string BufSize = 2;`
           */
          public fun clearBufSize() {
            _builder.clearBufSize()
          }
        }
      }
      @kotlin.jvm.JvmName("-initializehistoryValue")
      public inline fun historyValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.HistoryValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.HistoryValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.HistoryValue`
       */
      public object HistoryValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue = _builder.build()

          /**
           * ```
           *ISO8601 period expression
           * ```
           *
           * `string TimePeriod = 1;`
           */
          public var timePeriod: kotlin.String
            @JvmName("getTimePeriod")
            get() = _builder.getTimePeriod()
            @JvmName("setTimePeriod")
            set(value) {
              _builder.setTimePeriod(value)
            }
          /**
           * ```
           *ISO8601 period expression
           * ```
           *
           * `string TimePeriod = 1;`
           */
          public fun clearTimePeriod() {
            _builder.clearTimePeriod()
          }
        }
      }
      @kotlin.jvm.JvmName("-initializestaticMetadataValue")
      public inline fun staticMetadataValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.StaticMetadataValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.StaticMetadataValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue`
       */
      public object StaticMetadataValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue = _builder.build()

          /**
           * `string Tree = 1;`
           */
          public var tree: kotlin.String
            @JvmName("getTree")
            get() = _builder.getTree()
            @JvmName("setTree")
            set(value) {
              _builder.setTree(value)
            }
          /**
           * `string Tree = 1;`
           */
          public fun clearTree() {
            _builder.clearTree()
          }
        }
      }
      @kotlin.jvm.JvmName("-initializedynamicMetadataValue")
      public inline fun dynamicMetadataValue(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.DynamicMetadataValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue =
        grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.DynamicMetadataValueKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue.newBuilder()).apply { block() }._build()
      /**
       * Protobuf type `grpcProtobufMessages.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue`
       */
      public object DynamicMetadataValueKt {
        @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        @com.google.protobuf.kotlin.ProtoDslMarker
        public class Dsl private constructor(
          private val _builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue.Builder
        ) {
          public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue.Builder): Dsl = Dsl(builder)
          }

          @kotlin.jvm.JvmSynthetic
          @kotlin.PublishedApi
          internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue = _builder.build()

          /**
           * `string MetadataDomain = 1;`
           */
          public var metadataDomain: kotlin.String
            @JvmName("getMetadataDomain")
            get() = _builder.getMetadataDomain()
            @JvmName("setMetadataDomain")
            set(value) {
              _builder.setMetadataDomain(value)
            }
          /**
           * `string MetadataDomain = 1;`
           */
          public fun clearMetadataDomain() {
            _builder.clearMetadataDomain()
          }
        }
      }
    }
  }
}
public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.copy(block: grpcProtobufMessages.FilterExpressionsKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions =
  grpcProtobufMessages.FilterExpressionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.PathsValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.PathsValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.TimebasedValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.TimebasedValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.RangeValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.RangeValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.RangeValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.ChangeValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.ChangeValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.CurvelogValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.CurvelogValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.HistoryValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.HistoryValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.StaticMetadataValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.StaticMetadataValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue.copy(block: grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.DynamicMetadataValueKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue =
  grpcProtobufMessages.FilterExpressionsKt.FilterExpressionKt.FilterValueKt.DynamicMetadataValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValueOrBuilder.valuePathsOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.PathsValue?
  get() = if (hasValuePaths()) getValuePaths() else null

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValueOrBuilder.valueTimebasedOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.TimebasedValue?
  get() = if (hasValueTimebased()) getValueTimebased() else null

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValueOrBuilder.valueChangeOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.ChangeValue?
  get() = if (hasValueChange()) getValueChange() else null

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValueOrBuilder.valueCurvelogOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.CurvelogValue?
  get() = if (hasValueCurvelog()) getValueCurvelog() else null

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValueOrBuilder.valueHistoryOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.HistoryValue?
  get() = if (hasValueHistory()) getValueHistory() else null

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValueOrBuilder.valueStaticMetadataOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.StaticMetadataValue?
  get() = if (hasValueStaticMetadata()) getValueStaticMetadata() else null

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValueOrBuilder.valueDynamicMetadataOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue.DynamicMetadataValue?
  get() = if (hasValueDynamicMetadata()) getValueDynamicMetadata() else null

public val grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpressionOrBuilder.valueOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions.FilterExpression.FilterValue?
  get() = if (hasValue()) getValue() else null

