// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: VISSv2.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package grpcProtobufMessages;

@kotlin.jvm.JvmName("-initializegetRequestMessage")
public inline fun getRequestMessage(block: grpcProtobufMessages.GetRequestMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.GetRequestMessage =
  grpcProtobufMessages.GetRequestMessageKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.GetRequestMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpcProtobufMessages.GetRequestMessage`
 */
public object GetRequestMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpcProtobufMessages.VISSv2OuterClass.GetRequestMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.GetRequestMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.GetRequestMessage = _builder.build()

    /**
     * `string Path = 1;`
     */
    public var path: kotlin.String
      @JvmName("getPath")
      get() = _builder.getPath()
      @JvmName("setPath")
      set(value) {
        _builder.setPath(value)
      }
    /**
     * `string Path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `optional .grpcProtobufMessages.FilterExpressions Filter = 2;`
     */
    public var filter: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions
      @JvmName("getFilter")
      get() = _builder.getFilter()
      @JvmName("setFilter")
      set(value) {
        _builder.setFilter(value)
      }
    /**
     * `optional .grpcProtobufMessages.FilterExpressions Filter = 2;`
     */
    public fun clearFilter() {
      _builder.clearFilter()
    }
    /**
     * `optional .grpcProtobufMessages.FilterExpressions Filter = 2;`
     * @return Whether the filter field is set.
     */
    public fun hasFilter(): kotlin.Boolean {
      return _builder.hasFilter()
    }
    public val GetRequestMessageKt.Dsl.filterOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions?
      get() = _builder.filterOrNull

    /**
     * `optional string Authorization = 3;`
     */
    public var authorization: kotlin.String
      @JvmName("getAuthorization")
      get() = _builder.getAuthorization()
      @JvmName("setAuthorization")
      set(value) {
        _builder.setAuthorization(value)
      }
    /**
     * `optional string Authorization = 3;`
     */
    public fun clearAuthorization() {
      _builder.clearAuthorization()
    }
    /**
     * `optional string Authorization = 3;`
     * @return Whether the authorization field is set.
     */
    public fun hasAuthorization(): kotlin.Boolean {
      return _builder.hasAuthorization()
    }

    /**
     * `optional string RequestId = 4;`
     */
    public var requestId: kotlin.String
      @JvmName("getRequestId")
      get() = _builder.getRequestId()
      @JvmName("setRequestId")
      set(value) {
        _builder.setRequestId(value)
      }
    /**
     * `optional string RequestId = 4;`
     */
    public fun clearRequestId() {
      _builder.clearRequestId()
    }
    /**
     * `optional string RequestId = 4;`
     * @return Whether the requestId field is set.
     */
    public fun hasRequestId(): kotlin.Boolean {
      return _builder.hasRequestId()
    }
  }
}
public inline fun grpcProtobufMessages.VISSv2OuterClass.GetRequestMessage.copy(block: grpcProtobufMessages.GetRequestMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.GetRequestMessage =
  grpcProtobufMessages.GetRequestMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val grpcProtobufMessages.VISSv2OuterClass.GetRequestMessageOrBuilder.filterOrNull: grpcProtobufMessages.VISSv2OuterClass.FilterExpressions?
  get() = if (hasFilter()) getFilter() else null

