// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: VISSv2.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package grpcProtobufMessages;

@kotlin.jvm.JvmName("-initializegetResponseMessage")
public inline fun getResponseMessage(block: grpcProtobufMessages.GetResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage =
  grpcProtobufMessages.GetResponseMessageKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpcProtobufMessages.GetResponseMessage`
 */
public object GetResponseMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage = _builder.build()

    /**
     * `.grpcProtobufMessages.ResponseStatus Status = 1;`
     */
    public var status: grpcProtobufMessages.VISSv2OuterClass.ResponseStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.grpcProtobufMessages.ResponseStatus Status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `optional .grpcProtobufMessages.GetResponseMessage.SuccessResponseMessage SuccessResponse = 2;`
     */
    public var successResponse: grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage
      @JvmName("getSuccessResponse")
      get() = _builder.getSuccessResponse()
      @JvmName("setSuccessResponse")
      set(value) {
        _builder.setSuccessResponse(value)
      }
    /**
     * `optional .grpcProtobufMessages.GetResponseMessage.SuccessResponseMessage SuccessResponse = 2;`
     */
    public fun clearSuccessResponse() {
      _builder.clearSuccessResponse()
    }
    /**
     * `optional .grpcProtobufMessages.GetResponseMessage.SuccessResponseMessage SuccessResponse = 2;`
     * @return Whether the successResponse field is set.
     */
    public fun hasSuccessResponse(): kotlin.Boolean {
      return _builder.hasSuccessResponse()
    }
    public val GetResponseMessageKt.Dsl.successResponseOrNull: grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage?
      get() = _builder.successResponseOrNull

    /**
     * `optional .grpcProtobufMessages.ErrorResponseMessage ErrorResponse = 3;`
     */
    public var errorResponse: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage
      @JvmName("getErrorResponse")
      get() = _builder.getErrorResponse()
      @JvmName("setErrorResponse")
      set(value) {
        _builder.setErrorResponse(value)
      }
    /**
     * `optional .grpcProtobufMessages.ErrorResponseMessage ErrorResponse = 3;`
     */
    public fun clearErrorResponse() {
      _builder.clearErrorResponse()
    }
    /**
     * `optional .grpcProtobufMessages.ErrorResponseMessage ErrorResponse = 3;`
     * @return Whether the errorResponse field is set.
     */
    public fun hasErrorResponse(): kotlin.Boolean {
      return _builder.hasErrorResponse()
    }
    public val GetResponseMessageKt.Dsl.errorResponseOrNull: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage?
      get() = _builder.errorResponseOrNull

    /**
     * `optional string RequestId = 4;`
     */
    public var requestId: kotlin.String
      @JvmName("getRequestId")
      get() = _builder.getRequestId()
      @JvmName("setRequestId")
      set(value) {
        _builder.setRequestId(value)
      }
    /**
     * `optional string RequestId = 4;`
     */
    public fun clearRequestId() {
      _builder.clearRequestId()
    }
    /**
     * `optional string RequestId = 4;`
     * @return Whether the requestId field is set.
     */
    public fun hasRequestId(): kotlin.Boolean {
      return _builder.hasRequestId()
    }

    /**
     * `optional string Ts = 5;`
     */
    public var ts: kotlin.String
      @JvmName("getTs")
      get() = _builder.getTs()
      @JvmName("setTs")
      set(value) {
        _builder.setTs(value)
      }
    /**
     * `optional string Ts = 5;`
     */
    public fun clearTs() {
      _builder.clearTs()
    }
    /**
     * `optional string Ts = 5;`
     * @return Whether the ts field is set.
     */
    public fun hasTs(): kotlin.Boolean {
      return _builder.hasTs()
    }

    /**
     * <code>optional int32 TsC = 6;</code>
     */
    public var tsC: kotlin.Int
      @JvmName("getTsC")
      get() = _builder.getTsC()
      @JvmName("setTsC")
      set(value) {
        _builder.setTsC(value)
      }
    /**
     * `optional int32 TsC = 6;`
     */
    public fun clearTsC() {
      _builder.clearTsC()
    }
    /**
     * `optional int32 TsC = 6;`
     * @return Whether the tsC field is set.
     */
    public fun hasTsC(): kotlin.Boolean {
      return _builder.hasTsC()
    }
  }
  @kotlin.jvm.JvmName("-initializesuccessResponseMessage")
  public inline fun successResponseMessage(block: grpcProtobufMessages.GetResponseMessageKt.SuccessResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage =
    grpcProtobufMessages.GetResponseMessageKt.SuccessResponseMessageKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `grpcProtobufMessages.GetResponseMessage.SuccessResponseMessage`
   */
  public object SuccessResponseMessageKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage = _builder.build()

      /**
       * `optional .grpcProtobufMessages.DataPackages DataPack = 1;`
       */
      public var dataPack: grpcProtobufMessages.VISSv2OuterClass.DataPackages
        @JvmName("getDataPack")
        get() = _builder.getDataPack()
        @JvmName("setDataPack")
        set(value) {
          _builder.setDataPack(value)
        }
      /**
       * `optional .grpcProtobufMessages.DataPackages DataPack = 1;`
       */
      public fun clearDataPack() {
        _builder.clearDataPack()
      }
      /**
       * `optional .grpcProtobufMessages.DataPackages DataPack = 1;`
       * @return Whether the dataPack field is set.
       */
      public fun hasDataPack(): kotlin.Boolean {
        return _builder.hasDataPack()
      }
      public val SuccessResponseMessageKt.Dsl.dataPackOrNull: grpcProtobufMessages.VISSv2OuterClass.DataPackages?
        get() = _builder.dataPackOrNull

      /**
       * ```
       * replaces DataPack in static metadata and one dynamic metadata variant
       * ```
       *
       * `optional string Metadata = 2;`
       */
      public var metadata: kotlin.String
        @JvmName("getMetadata")
        get() = _builder.getMetadata()
        @JvmName("setMetadata")
        set(value) {
          _builder.setMetadata(value)
        }
      /**
       * ```
       * replaces DataPack in static metadata and one dynamic metadata variant
       * ```
       *
       * `optional string Metadata = 2;`
       */
      public fun clearMetadata() {
        _builder.clearMetadata()
      }
      /**
       * ```
       * replaces DataPack in static metadata and one dynamic metadata variant
       * ```
       *
       * `optional string Metadata = 2;`
       * @return Whether the metadata field is set.
       */
      public fun hasMetadata(): kotlin.Boolean {
        return _builder.hasMetadata()
      }
    }
  }
}
public inline fun grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.copy(block: grpcProtobufMessages.GetResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage =
  grpcProtobufMessages.GetResponseMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage.copy(block: grpcProtobufMessages.GetResponseMessageKt.SuccessResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage =
  grpcProtobufMessages.GetResponseMessageKt.SuccessResponseMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessageOrBuilder.dataPackOrNull: grpcProtobufMessages.VISSv2OuterClass.DataPackages?
  get() = if (hasDataPack()) getDataPack() else null

public val grpcProtobufMessages.VISSv2OuterClass.GetResponseMessageOrBuilder.successResponseOrNull: grpcProtobufMessages.VISSv2OuterClass.GetResponseMessage.SuccessResponseMessage?
  get() = if (hasSuccessResponse()) getSuccessResponse() else null

public val grpcProtobufMessages.VISSv2OuterClass.GetResponseMessageOrBuilder.errorResponseOrNull: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage?
  get() = if (hasErrorResponse()) getErrorResponse() else null

