// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: VISSv2.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package grpcProtobufMessages;

@kotlin.jvm.JvmName("-initializesetResponseMessage")
public inline fun setResponseMessage(block: grpcProtobufMessages.SetResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.SetResponseMessage =
  grpcProtobufMessages.SetResponseMessageKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.SetResponseMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpcProtobufMessages.SetResponseMessage`
 */
public object SetResponseMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpcProtobufMessages.VISSv2OuterClass.SetResponseMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.SetResponseMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.SetResponseMessage = _builder.build()

    /**
     * `.grpcProtobufMessages.ResponseStatus Status = 1;`
     */
    public var status: grpcProtobufMessages.VISSv2OuterClass.ResponseStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.grpcProtobufMessages.ResponseStatus Status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `optional .grpcProtobufMessages.ErrorResponseMessage ErrorResponse = 2;`
     */
    public var errorResponse: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage
      @JvmName("getErrorResponse")
      get() = _builder.getErrorResponse()
      @JvmName("setErrorResponse")
      set(value) {
        _builder.setErrorResponse(value)
      }
    /**
     * `optional .grpcProtobufMessages.ErrorResponseMessage ErrorResponse = 2;`
     */
    public fun clearErrorResponse() {
      _builder.clearErrorResponse()
    }
    /**
     * `optional .grpcProtobufMessages.ErrorResponseMessage ErrorResponse = 2;`
     * @return Whether the errorResponse field is set.
     */
    public fun hasErrorResponse(): kotlin.Boolean {
      return _builder.hasErrorResponse()
    }
    public val SetResponseMessageKt.Dsl.errorResponseOrNull: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage?
      get() = _builder.errorResponseOrNull

    /**
     * `optional string RequestId = 3;`
     */
    public var requestId: kotlin.String
      @JvmName("getRequestId")
      get() = _builder.getRequestId()
      @JvmName("setRequestId")
      set(value) {
        _builder.setRequestId(value)
      }
    /**
     * `optional string RequestId = 3;`
     */
    public fun clearRequestId() {
      _builder.clearRequestId()
    }
    /**
     * `optional string RequestId = 3;`
     * @return Whether the requestId field is set.
     */
    public fun hasRequestId(): kotlin.Boolean {
      return _builder.hasRequestId()
    }

    /**
     * `string Ts = 4;`
     */
    public var ts: kotlin.String
      @JvmName("getTs")
      get() = _builder.getTs()
      @JvmName("setTs")
      set(value) {
        _builder.setTs(value)
      }
    /**
     * `string Ts = 4;`
     */
    public fun clearTs() {
      _builder.clearTs()
    }
  }
}
public inline fun grpcProtobufMessages.VISSv2OuterClass.SetResponseMessage.copy(block: grpcProtobufMessages.SetResponseMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.SetResponseMessage =
  grpcProtobufMessages.SetResponseMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val grpcProtobufMessages.VISSv2OuterClass.SetResponseMessageOrBuilder.errorResponseOrNull: grpcProtobufMessages.VISSv2OuterClass.ErrorResponseMessage?
  get() = if (hasErrorResponse()) getErrorResponse() else null

