// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: VISSv2.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package grpcProtobufMessages;

@kotlin.jvm.JvmName("-initializeunsubscribeRequestMessage")
public inline fun unsubscribeRequestMessage(block: grpcProtobufMessages.UnsubscribeRequestMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.UnsubscribeRequestMessage =
  grpcProtobufMessages.UnsubscribeRequestMessageKt.Dsl._create(grpcProtobufMessages.VISSv2OuterClass.UnsubscribeRequestMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpcProtobufMessages.UnsubscribeRequestMessage`
 */
public object UnsubscribeRequestMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpcProtobufMessages.VISSv2OuterClass.UnsubscribeRequestMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpcProtobufMessages.VISSv2OuterClass.UnsubscribeRequestMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpcProtobufMessages.VISSv2OuterClass.UnsubscribeRequestMessage = _builder.build()

    /**
     * `string SubscriptionId = 1;`
     */
    public var subscriptionId: kotlin.String
      @JvmName("getSubscriptionId")
      get() = _builder.getSubscriptionId()
      @JvmName("setSubscriptionId")
      set(value) {
        _builder.setSubscriptionId(value)
      }
    /**
     * `string SubscriptionId = 1;`
     */
    public fun clearSubscriptionId() {
      _builder.clearSubscriptionId()
    }

    /**
     * `optional string RequestId = 2;`
     */
    public var requestId: kotlin.String
      @JvmName("getRequestId")
      get() = _builder.getRequestId()
      @JvmName("setRequestId")
      set(value) {
        _builder.setRequestId(value)
      }
    /**
     * `optional string RequestId = 2;`
     */
    public fun clearRequestId() {
      _builder.clearRequestId()
    }
    /**
     * `optional string RequestId = 2;`
     * @return Whether the requestId field is set.
     */
    public fun hasRequestId(): kotlin.Boolean {
      return _builder.hasRequestId()
    }
  }
}
public inline fun grpcProtobufMessages.VISSv2OuterClass.UnsubscribeRequestMessage.copy(block: grpcProtobufMessages.UnsubscribeRequestMessageKt.Dsl.() -> kotlin.Unit): grpcProtobufMessages.VISSv2OuterClass.UnsubscribeRequestMessage =
  grpcProtobufMessages.UnsubscribeRequestMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

