//*
// (C) 2026 Ford Motor Company
// (C) 2024 Ford Motor Company
// (C) 2021 Geotab
//
// All files and artifacts in the repository at https://github.com/covesa/vissr
// are licensed under the provisions of the license provided by the LICENSE file in this repository.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: VISSv3.2.5.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VISS_GetRequest_FullMethodName         = "/grpcProtobufMessages.VISS/GetRequest"
	VISS_SetRequest_FullMethodName         = "/grpcProtobufMessages.VISS/SetRequest"
	VISS_SubscribeRequest_FullMethodName   = "/grpcProtobufMessages.VISS/SubscribeRequest"
	VISS_UnsubscribeRequest_FullMethodName = "/grpcProtobufMessages.VISS/UnsubscribeRequest"
	VISS_InvokeRequest_FullMethodName      = "/grpcProtobufMessages.VISS/InvokeRequest"
	VISS_MonitorRequest_FullMethodName     = "/grpcProtobufMessages.VISS/MonitorRequest"
	VISS_CancelRequest_FullMethodName      = "/grpcProtobufMessages.VISS/CancelRequest"
	VISS_DiscoverRequest_FullMethodName    = "/grpcProtobufMessages.VISS/DiscoverRequest"
)

// VISSClient is the client API for VISS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VISSClient interface {
	GetRequest(ctx context.Context, in *GetRequestMessage, opts ...grpc.CallOption) (*GetResponseMessage, error)
	SetRequest(ctx context.Context, in *SetRequestMessage, opts ...grpc.CallOption) (*SetResponseMessage, error)
	SubscribeRequest(ctx context.Context, in *SubscribeRequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeStreamMessage], error)
	UnsubscribeRequest(ctx context.Context, in *UnsubscribeRequestMessage, opts ...grpc.CallOption) (*UnsubscribeResponseMessage, error)
	// VISSv3.2 Service profile (VehicleService.* trees). InvokeRequest and
	// MonitorRequest are server-streaming: the first message is the
	// synchronous ACK/response, and if its status is ONGOING, monitoring
	// events for the same session follow until a terminal status is reached.
	InvokeRequest(ctx context.Context, in *InvokeRequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeStreamMessage], error)
	MonitorRequest(ctx context.Context, in *MonitorRequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorStreamMessage], error)
	CancelRequest(ctx context.Context, in *CancelRequestMessage, opts ...grpc.CallOption) (*CancelResponseMessage, error)
	DiscoverRequest(ctx context.Context, in *DiscoverRequestMessage, opts ...grpc.CallOption) (*DiscoverResponseMessage, error)
}

type vISSClient struct {
	cc grpc.ClientConnInterface
}

func NewVISSClient(cc grpc.ClientConnInterface) VISSClient {
	return &vISSClient{cc}
}

func (c *vISSClient) GetRequest(ctx context.Context, in *GetRequestMessage, opts ...grpc.CallOption) (*GetResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponseMessage)
	err := c.cc.Invoke(ctx, VISS_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vISSClient) SetRequest(ctx context.Context, in *SetRequestMessage, opts ...grpc.CallOption) (*SetResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponseMessage)
	err := c.cc.Invoke(ctx, VISS_SetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vISSClient) SubscribeRequest(ctx context.Context, in *SubscribeRequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VISS_ServiceDesc.Streams[0], VISS_SubscribeRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequestMessage, SubscribeStreamMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VISS_SubscribeRequestClient = grpc.ServerStreamingClient[SubscribeStreamMessage]

func (c *vISSClient) UnsubscribeRequest(ctx context.Context, in *UnsubscribeRequestMessage, opts ...grpc.CallOption) (*UnsubscribeResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponseMessage)
	err := c.cc.Invoke(ctx, VISS_UnsubscribeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vISSClient) InvokeRequest(ctx context.Context, in *InvokeRequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VISS_ServiceDesc.Streams[1], VISS_InvokeRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeRequestMessage, InvokeStreamMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VISS_InvokeRequestClient = grpc.ServerStreamingClient[InvokeStreamMessage]

func (c *vISSClient) MonitorRequest(ctx context.Context, in *MonitorRequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VISS_ServiceDesc.Streams[2], VISS_MonitorRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MonitorRequestMessage, MonitorStreamMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VISS_MonitorRequestClient = grpc.ServerStreamingClient[MonitorStreamMessage]

func (c *vISSClient) CancelRequest(ctx context.Context, in *CancelRequestMessage, opts ...grpc.CallOption) (*CancelResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponseMessage)
	err := c.cc.Invoke(ctx, VISS_CancelRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vISSClient) DiscoverRequest(ctx context.Context, in *DiscoverRequestMessage, opts ...grpc.CallOption) (*DiscoverResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverResponseMessage)
	err := c.cc.Invoke(ctx, VISS_DiscoverRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VISSServer is the server API for VISS service.
// All implementations must embed UnimplementedVISSServer
// for forward compatibility.
type VISSServer interface {
	GetRequest(context.Context, *GetRequestMessage) (*GetResponseMessage, error)
	SetRequest(context.Context, *SetRequestMessage) (*SetResponseMessage, error)
	SubscribeRequest(*SubscribeRequestMessage, grpc.ServerStreamingServer[SubscribeStreamMessage]) error
	UnsubscribeRequest(context.Context, *UnsubscribeRequestMessage) (*UnsubscribeResponseMessage, error)
	// VISSv3.2 Service profile (VehicleService.* trees). InvokeRequest and
	// MonitorRequest are server-streaming: the first message is the
	// synchronous ACK/response, and if its status is ONGOING, monitoring
	// events for the same session follow until a terminal status is reached.
	InvokeRequest(*InvokeRequestMessage, grpc.ServerStreamingServer[InvokeStreamMessage]) error
	MonitorRequest(*MonitorRequestMessage, grpc.ServerStreamingServer[MonitorStreamMessage]) error
	CancelRequest(context.Context, *CancelRequestMessage) (*CancelResponseMessage, error)
	DiscoverRequest(context.Context, *DiscoverRequestMessage) (*DiscoverResponseMessage, error)
	mustEmbedUnimplementedVISSServer()
}

// UnimplementedVISSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVISSServer struct{}

func (UnimplementedVISSServer) GetRequest(context.Context, *GetRequestMessage) (*GetResponseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedVISSServer) SetRequest(context.Context, *SetRequestMessage) (*SetResponseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRequest not implemented")
}
func (UnimplementedVISSServer) SubscribeRequest(*SubscribeRequestMessage, grpc.ServerStreamingServer[SubscribeStreamMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRequest not implemented")
}
func (UnimplementedVISSServer) UnsubscribeRequest(context.Context, *UnsubscribeRequestMessage) (*UnsubscribeResponseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeRequest not implemented")
}
func (UnimplementedVISSServer) InvokeRequest(*InvokeRequestMessage, grpc.ServerStreamingServer[InvokeStreamMessage]) error {
	return status.Error(codes.Unimplemented, "method InvokeRequest not implemented")
}
func (UnimplementedVISSServer) MonitorRequest(*MonitorRequestMessage, grpc.ServerStreamingServer[MonitorStreamMessage]) error {
	return status.Error(codes.Unimplemented, "method MonitorRequest not implemented")
}
func (UnimplementedVISSServer) CancelRequest(context.Context, *CancelRequestMessage) (*CancelResponseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRequest not implemented")
}
func (UnimplementedVISSServer) DiscoverRequest(context.Context, *DiscoverRequestMessage) (*DiscoverResponseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverRequest not implemented")
}
func (UnimplementedVISSServer) mustEmbedUnimplementedVISSServer() {}
func (UnimplementedVISSServer) testEmbeddedByValue()              {}

// UnsafeVISSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VISSServer will
// result in compilation errors.
type UnsafeVISSServer interface {
	mustEmbedUnimplementedVISSServer()
}

func RegisterVISSServer(s grpc.ServiceRegistrar, srv VISSServer) {
	// If the following call panics, it indicates UnimplementedVISSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VISS_ServiceDesc, srv)
}

func _VISS_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VISSServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VISS_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VISSServer).GetRequest(ctx, req.(*GetRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _VISS_SetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VISSServer).SetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VISS_SetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VISSServer).SetRequest(ctx, req.(*SetRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _VISS_SubscribeRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VISSServer).SubscribeRequest(m, &grpc.GenericServerStream[SubscribeRequestMessage, SubscribeStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VISS_SubscribeRequestServer = grpc.ServerStreamingServer[SubscribeStreamMessage]

func _VISS_UnsubscribeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VISSServer).UnsubscribeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VISS_UnsubscribeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VISSServer).UnsubscribeRequest(ctx, req.(*UnsubscribeRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _VISS_InvokeRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VISSServer).InvokeRequest(m, &grpc.GenericServerStream[InvokeRequestMessage, InvokeStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VISS_InvokeRequestServer = grpc.ServerStreamingServer[InvokeStreamMessage]

func _VISS_MonitorRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorRequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VISSServer).MonitorRequest(m, &grpc.GenericServerStream[MonitorRequestMessage, MonitorStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VISS_MonitorRequestServer = grpc.ServerStreamingServer[MonitorStreamMessage]

func _VISS_CancelRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VISSServer).CancelRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VISS_CancelRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VISSServer).CancelRequest(ctx, req.(*CancelRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _VISS_DiscoverRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VISSServer).DiscoverRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VISS_DiscoverRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VISSServer).DiscoverRequest(ctx, req.(*DiscoverRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// VISS_ServiceDesc is the grpc.ServiceDesc for VISS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VISS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcProtobufMessages.VISS",
	HandlerType: (*VISSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRequest",
			Handler:    _VISS_GetRequest_Handler,
		},
		{
			MethodName: "SetRequest",
			Handler:    _VISS_SetRequest_Handler,
		},
		{
			MethodName: "UnsubscribeRequest",
			Handler:    _VISS_UnsubscribeRequest_Handler,
		},
		{
			MethodName: "CancelRequest",
			Handler:    _VISS_CancelRequest_Handler,
		},
		{
			MethodName: "DiscoverRequest",
			Handler:    _VISS_DiscoverRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRequest",
			Handler:       _VISS_SubscribeRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InvokeRequest",
			Handler:       _VISS_InvokeRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MonitorRequest",
			Handler:       _VISS_MonitorRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "VISSv3.2.5.proto",
}
